# Soda's test and deploy workflow

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ '**' ]
    tags: [ "v*" ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Test the add-on
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        blender-version: ["3.0"]
        os: [ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      # Create the addon's zip
      - name: Package
        shell: bash
        run: |
          zip -9 -r soda.zip soda
      # Pull requests and non-main branches store artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: soda_artifacts
          path: |
            soda.zip
  # Deploy the add-on
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Download all built artifacts
        uses: actions/download-artifact@v2
      # Pushes deploy to development build
      - name: "Development Build release"
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.event_name == 'push' && startswith(github.ref, 'refs/heads/main') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: soda_artifacts/*.zip
      # Tags deploy to named release
      - name: "Tagged release"
        uses: "marvinpinto/action-automatic-releases@latest"
        if: ${{ github.event_name == 'push' && startswith(github.ref, 'refs/tags/') }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: soda_artifacts/*.zip
